// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: test ac1 june 12

#ifndef _TEST_AC1_JUNE_12_UI_H
#define _TEST_AC1_JUNE_12_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_heater_ui_bg_png_png);    // assets/HEATER UI BG png.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/Settings.png

// FONTS
LV_FONT_DECLARE(ui_font_BigSan);
LV_FONT_DECLARE(ui_font_MedSan);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
