// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project test ac1

#include "ui.h"

void Fan_Speed(lv_event_t * e)
{
	// Your code here
}

void enableRearhvac(lv_event_t * e)
{
	// Your code here
}

void enableRightVent(lv_event_t * e)
{
	// Your code here
}

void enableDown(lv_event_t * e)
{
	// Your code here
}

void enableUp(lv_event_t * e)
{
	// Your code here
}

void enableRight(lv_event_t * e)
{
	// Your code here
}

void enableLeft(lv_event_t * e)
{
	// Your code here
}

void enableEnter(lv_event_t * e)
{
	// Your code here
}

void enableHud(lv_event_t * e)
{
	// Your code here
}

void enableSystem(lv_event_t * e)
{
	// Your code here
}

void enableFloor(lv_event_t * e)
{
	// Your code here
}

void enablePanel(lv_event_t * e)
{
	// Your code here
}

void enableDefrost(lv_event_t * e)
{
	// Your code here
}

void enableReardefrost(lv_event_t * e)
{
	// Your code here
}

void enableRecirc(lv_event_t * e)
{
	// Your code here
}

void enableLeftvent(lv_event_t * e)
{
	// Your code here
}

void FanSpeed(lv_event_t * e)
{
	// Your code here
}

void FanSpeedSet(lv_event_t * e)
{
	// Your code here
}
