// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: test ac1 june 12

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void enableSystem(lv_event_t * e);
void FanSpeedSet(lv_event_t * e);
void enableFloor(lv_event_t * e);
void enablePanel(lv_event_t * e);
void enableDefrost(lv_event_t * e);
void enableReardefrost(lv_event_t * e);
void enableRecirc(lv_event_t * e);
void enableRearhvac(lv_event_t * e);
void enableDown(lv_event_t * e);
void enableUp(lv_event_t * e);
void enableRight(lv_event_t * e);
void enableLeft(lv_event_t * e);
void enableEnter(lv_event_t * e);
void enableLeftvent(lv_event_t * e);
void enableRightVent(lv_event_t * e);
void enableHud(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
