// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: test ac1 june 12

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_ButtonHVACSCREEN = NULL;
lv_obj_t * ui_LabelHVACSCREEN = NULL;
lv_obj_t * ui_ButtonDOWN = NULL;
lv_obj_t * ui_LabelDOWN = NULL;
lv_obj_t * ui_ButtonUP = NULL;
lv_obj_t * ui_LabelUP = NULL;
lv_obj_t * ui_ButtonRIGHT = NULL;
lv_obj_t * ui_LabelRIGHT = NULL;
lv_obj_t * ui_ButtonLEFT = NULL;
lv_obj_t * ui_LabelLEFT = NULL;
lv_obj_t * ui_ButtonENTER = NULL;
lv_obj_t * ui_LabelENTER = NULL;
lv_obj_t * ui_ButtonLEFTVENT = NULL;
lv_obj_t * ui_LabelLEFTVENT = NULL;
lv_obj_t * ui_ButtonRIGHTVENT = NULL;
lv_obj_t * ui_LabelRIGHTVENT = NULL;
lv_obj_t * ui_ButtonHUD = NULL;
lv_obj_t * ui_LabelHUD = NULL;
// event funtions
void ui_event_ButtonHVACSCREEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_ButtonDOWN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableDown(e);
    }
}

void ui_event_ButtonUP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableUp(e);
    }
}

void ui_event_ButtonRIGHT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableRight(e);
    }
}

void ui_event_ButtonLEFT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableLeft(e);
    }
}

void ui_event_ButtonENTER(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableEnter(e);
    }
}

void ui_event_ButtonLEFTVENT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableLeftvent(e);
    }
}

void ui_event_ButtonRIGHTVENT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableRightVent(e);
    }
}

void ui_event_ButtonHUD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        enableHud(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonHVACSCREEN = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonHVACSCREEN, 100);
    lv_obj_set_height(ui_ButtonHVACSCREEN, 50);
    lv_obj_set_x(ui_ButtonHVACSCREEN, 164);
    lv_obj_set_y(ui_ButtonHVACSCREEN, -116);
    lv_obj_set_align(ui_ButtonHVACSCREEN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonHVACSCREEN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonHVACSCREEN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHVACSCREEN = lv_label_create(ui_ButtonHVACSCREEN);
    lv_obj_set_width(ui_LabelHVACSCREEN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHVACSCREEN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHVACSCREEN, 0);
    lv_obj_set_y(ui_LabelHVACSCREEN, 1);
    lv_obj_set_align(ui_LabelHVACSCREEN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHVACSCREEN, "  HVAC\nSCREEN");

    ui_ButtonDOWN = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonDOWN, 61);
    lv_obj_set_height(ui_ButtonDOWN, 50);
    lv_obj_set_x(ui_ButtonDOWN, -32);
    lv_obj_set_y(ui_ButtonDOWN, 106);
    lv_obj_set_align(ui_ButtonDOWN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDOWN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonDOWN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonDOWN, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDOWN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDOWN, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonDOWN, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelDOWN = lv_label_create(ui_ButtonDOWN);
    lv_obj_set_width(ui_LabelDOWN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDOWN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelDOWN, 2);
    lv_obj_set_x(ui_LabelDOWN, lv_pct(0));
    lv_obj_set_align(ui_LabelDOWN, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelDOWN, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelDOWN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelDOWN, "DOWN");
    lv_obj_set_style_text_font(ui_LabelDOWN, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonUP = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonUP, 61);
    lv_obj_set_height(ui_ButtonUP, 50);
    lv_obj_set_x(ui_ButtonUP, -34);
    lv_obj_set_y(ui_ButtonUP, -35);
    lv_obj_set_align(ui_ButtonUP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonUP, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonUP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonUP, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonUP, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelUP = lv_label_create(ui_ButtonUP);
    lv_obj_set_width(ui_LabelUP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelUP, 2);
    lv_obj_set_x(ui_LabelUP, lv_pct(0));
    lv_obj_set_align(ui_LabelUP, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelUP, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelUP, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelUP, "UP");
    lv_obj_set_style_text_font(ui_LabelUP, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRIGHT = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonRIGHT, 61);
    lv_obj_set_height(ui_ButtonRIGHT, 50);
    lv_obj_set_x(ui_ButtonRIGHT, 37);
    lv_obj_set_y(ui_ButtonRIGHT, 37);
    lv_obj_set_align(ui_ButtonRIGHT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRIGHT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonRIGHT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRIGHT, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRIGHT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonRIGHT, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonRIGHT, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelRIGHT = lv_label_create(ui_ButtonRIGHT);
    lv_obj_set_width(ui_LabelRIGHT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRIGHT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelRIGHT, 2);
    lv_obj_set_x(ui_LabelRIGHT, lv_pct(0));
    lv_obj_set_align(ui_LabelRIGHT, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelRIGHT, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelRIGHT, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelRIGHT, "RIGHT");
    lv_obj_set_style_text_font(ui_LabelRIGHT, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLEFT = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonLEFT, 61);
    lv_obj_set_height(ui_ButtonLEFT, 50);
    lv_obj_set_x(ui_ButtonLEFT, -97);
    lv_obj_set_y(ui_ButtonLEFT, 37);
    lv_obj_set_align(ui_ButtonLEFT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLEFT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonLEFT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLEFT, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLEFT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonLEFT, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonLEFT, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelLEFT = lv_label_create(ui_ButtonLEFT);
    lv_obj_set_width(ui_LabelLEFT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLEFT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelLEFT, 2);
    lv_obj_set_x(ui_LabelLEFT, lv_pct(3));
    lv_obj_set_align(ui_LabelLEFT, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelLEFT, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelLEFT, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelLEFT, "LEFT");
    lv_obj_set_style_text_font(ui_LabelLEFT, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonENTER = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonENTER, 61);
    lv_obj_set_height(ui_ButtonENTER, 50);
    lv_obj_set_x(ui_ButtonENTER, -31);
    lv_obj_set_y(ui_ButtonENTER, 38);
    lv_obj_set_align(ui_ButtonENTER, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonENTER, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonENTER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonENTER, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonENTER, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonENTER, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonENTER, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelENTER = lv_label_create(ui_ButtonENTER);
    lv_obj_set_width(ui_LabelENTER, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelENTER, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelENTER, 2);
    lv_obj_set_x(ui_LabelENTER, lv_pct(4));
    lv_obj_set_align(ui_LabelENTER, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelENTER, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelENTER, "ENTER");
    lv_obj_set_style_text_font(ui_LabelENTER, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLEFTVENT = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonLEFTVENT, 61);
    lv_obj_set_height(ui_ButtonLEFTVENT, 50);
    lv_obj_set_x(ui_ButtonLEFTVENT, -183);
    lv_obj_set_y(ui_ButtonLEFTVENT, -113);
    lv_obj_set_align(ui_ButtonLEFTVENT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLEFTVENT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonLEFTVENT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonLEFTVENT, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonLEFTVENT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonLEFTVENT, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonLEFTVENT, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelLEFTVENT = lv_label_create(ui_ButtonLEFTVENT);
    lv_obj_set_width(ui_LabelLEFTVENT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLEFTVENT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelLEFTVENT, 2);
    lv_obj_set_x(ui_LabelLEFTVENT, lv_pct(3));
    lv_obj_set_align(ui_LabelLEFTVENT, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelLEFTVENT, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelLEFTVENT, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelLEFTVENT, "LEFT\nVENT");
    lv_obj_set_style_text_font(ui_LabelLEFTVENT, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRIGHTVENT = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonRIGHTVENT, 61);
    lv_obj_set_height(ui_ButtonRIGHTVENT, 50);
    lv_obj_set_x(ui_ButtonRIGHTVENT, -73);
    lv_obj_set_y(ui_ButtonRIGHTVENT, -110);
    lv_obj_set_align(ui_ButtonRIGHTVENT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRIGHTVENT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonRIGHTVENT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRIGHTVENT, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRIGHTVENT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonRIGHTVENT, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonRIGHTVENT, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelRIGHTVENT = lv_label_create(ui_ButtonRIGHTVENT);
    lv_obj_set_width(ui_LabelRIGHTVENT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRIGHTVENT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelRIGHTVENT, 2);
    lv_obj_set_x(ui_LabelRIGHTVENT, lv_pct(3));
    lv_obj_set_align(ui_LabelRIGHTVENT, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelRIGHTVENT, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelRIGHTVENT, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelRIGHTVENT, "RIGHT\nVENT");
    lv_obj_set_style_text_font(ui_LabelRIGHTVENT, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonHUD = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_ButtonHUD, 61);
    lv_obj_set_height(ui_ButtonHUD, 50);
    lv_obj_set_x(ui_ButtonHUD, -193);
    lv_obj_set_y(ui_ButtonHUD, 121);
    lv_obj_set_align(ui_ButtonHUD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonHUD, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonHUD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonHUD, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonHUD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonHUD, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonHUD, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelHUD = lv_label_create(ui_ButtonHUD);
    lv_obj_set_width(ui_LabelHUD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHUD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelHUD, 2);
    lv_obj_set_x(ui_LabelHUD, lv_pct(3));
    lv_obj_set_align(ui_LabelHUD, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelHUD, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelHUD, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelHUD, "HUD");
    lv_obj_set_style_text_font(ui_LabelHUD, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonHVACSCREEN, ui_event_ButtonHVACSCREEN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonDOWN, ui_event_ButtonDOWN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonUP, ui_event_ButtonUP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRIGHT, ui_event_ButtonRIGHT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonLEFT, ui_event_ButtonLEFT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonENTER, ui_event_ButtonENTER, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonLEFTVENT, ui_event_ButtonLEFTVENT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRIGHTVENT, ui_event_ButtonRIGHTVENT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonHUD, ui_event_ButtonHUD, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_ButtonHVACSCREEN = NULL;
    ui_LabelHVACSCREEN = NULL;
    ui_ButtonDOWN = NULL;
    ui_LabelDOWN = NULL;
    ui_ButtonUP = NULL;
    ui_LabelUP = NULL;
    ui_ButtonRIGHT = NULL;
    ui_LabelRIGHT = NULL;
    ui_ButtonLEFT = NULL;
    ui_LabelLEFT = NULL;
    ui_ButtonENTER = NULL;
    ui_LabelENTER = NULL;
    ui_ButtonLEFTVENT = NULL;
    ui_LabelLEFTVENT = NULL;
    ui_ButtonRIGHTVENT = NULL;
    ui_LabelRIGHTVENT = NULL;
    ui_ButtonHUD = NULL;
    ui_LabelHUD = NULL;

}
