// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: test ac1 june 12

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ButtonAC = NULL;
lv_obj_t * ui_Labelac = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Sliderfan = NULL;
lv_obj_t * ui_Sliderleft = NULL;
lv_obj_t * ui_Sliderright = NULL;
lv_obj_t * ui_ButtonFLOOR = NULL;
lv_obj_t * ui_LabelFLOOR = NULL;
lv_obj_t * ui_ButtonPANEL = NULL;
lv_obj_t * ui_LabelPANEL = NULL;
lv_obj_t * ui_ButtonDEFROST = NULL;
lv_obj_t * ui_LabelDEFROST = NULL;
lv_obj_t * ui_ButtonSCREEN2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_ButtonREARDEF = NULL;
lv_obj_t * ui_LabelREARDEFROST = NULL;
lv_obj_t * ui_LabelLEFTTEMP = NULL;
lv_obj_t * ui_LabellRIGHTTEMP = NULL;
lv_obj_t * ui_LabellFanSegment = NULL;
lv_obj_t * ui_LabelFANSPEED = NULL;
lv_obj_t * ui_ButtonRecirc = NULL;
lv_obj_t * ui_LabelRecirc = NULL;
lv_obj_t * ui_ButtonRearhvac = NULL;
lv_obj_t * ui_LabelREARhvac = NULL;
// event funtions
void ui_event_ButtonAC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableSystem(e);
    }
}

void ui_event_Sliderfan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FanSpeedSet(e);
    }
}

void ui_event_ButtonFLOOR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableFloor(e);
    }
}

void ui_event_ButtonPANEL(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enablePanel(e);
    }
}

void ui_event_ButtonDEFROST(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableDefrost(e);
    }
}

void ui_event_ButtonSCREEN2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_ButtonREARDEF(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableReardefrost(e);
    }
}

void ui_event_ButtonRecirc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableRecirc(e);
    }
}

void ui_event_ButtonRearhvac(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableRecirc(e);
    }
}

void ui_event_LabelREARhvac(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        enableRearhvac(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0D0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_heater_ui_bg_png_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonAC = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonAC, 61);
    lv_obj_set_height(ui_ButtonAC, 50);
    lv_obj_set_x(ui_ButtonAC, -104);
    lv_obj_set_y(ui_ButtonAC, 106);
    lv_obj_set_align(ui_ButtonAC, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAC, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonAC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonAC, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonAC, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonAC, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Labelac = lv_label_create(ui_ButtonAC);
    lv_obj_set_width(ui_Labelac, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Labelac, 2);
    lv_obj_set_x(ui_Labelac, lv_pct(0));
    lv_obj_set_align(ui_Labelac, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Labelac, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Labelac, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Labelac, "AC");
    lv_obj_set_style_text_font(ui_Labelac, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -176);
    lv_obj_set_y(ui_Button2, -128);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xC7DBEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xE8ACAC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Sliderfan = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Sliderfan, 0, 10);
    lv_slider_set_value(ui_Sliderfan, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Sliderfan) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Sliderfan, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Sliderfan, 267);
    lv_obj_set_height(ui_Sliderfan, 35);
    lv_obj_set_x(ui_Sliderfan, 0);
    lv_obj_set_y(ui_Sliderfan, -75);
    lv_obj_set_align(ui_Sliderfan, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Sliderfan, lv_color_hex(0x0F0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderfan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Sliderfan, lv_color_hex(0x080909), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderfan, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Sliderfan, lv_color_hex(0xB6F0DB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderfan, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Sliderfan, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Sliderfan,
                                                                                                lv_obj_get_style_pad_right(ui_Sliderfan, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Sliderleft = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Sliderleft, 0, 24);
    lv_slider_set_value(ui_Sliderleft, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Sliderleft) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Sliderleft, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Sliderleft, 35);
    lv_obj_set_height(ui_Sliderleft, 150);
    lv_obj_set_x(ui_Sliderleft, -201);
    lv_obj_set_y(ui_Sliderleft, 71);
    lv_obj_set_align(ui_Sliderleft, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Sliderleft, lv_color_hex(0x0F0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderleft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Sliderleft, lv_color_hex(0xB6F0DB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderleft, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Sliderleft, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Sliderleft,
                                                                                                 lv_obj_get_style_pad_right(ui_Sliderleft, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Sliderright = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Sliderright, 0, 24);
    lv_slider_set_value(ui_Sliderright, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Sliderright) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Sliderright, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Sliderright, 35);
    lv_obj_set_height(ui_Sliderright, 150);
    lv_obj_set_x(ui_Sliderright, 201);
    lv_obj_set_y(ui_Sliderright, 71);
    lv_obj_set_align(ui_Sliderright, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Sliderright, lv_color_hex(0x0F0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderright, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Sliderright, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Sliderright, lv_color_hex(0x140F0F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderright, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Sliderright, lv_color_hex(0xB6F0DB), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sliderright, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Sliderright, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Sliderright,
                                                                                                  lv_obj_get_style_pad_right(ui_Sliderright, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ButtonFLOOR = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonFLOOR, 61);
    lv_obj_set_height(ui_ButtonFLOOR, 50);
    lv_obj_set_x(ui_ButtonFLOOR, -32);
    lv_obj_set_y(ui_ButtonFLOOR, 106);
    lv_obj_set_align(ui_ButtonFLOOR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonFLOOR, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonFLOOR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonFLOOR, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonFLOOR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonFLOOR, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonFLOOR, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelFLOOR = lv_label_create(ui_ButtonFLOOR);
    lv_obj_set_width(ui_LabelFLOOR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFLOOR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelFLOOR, 2);
    lv_obj_set_x(ui_LabelFLOOR, lv_pct(0));
    lv_obj_set_align(ui_LabelFLOOR, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelFLOOR, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelFLOOR, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelFLOOR, "FLOOR");
    lv_obj_set_style_text_font(ui_LabelFLOOR, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPANEL = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonPANEL, 61);
    lv_obj_set_height(ui_ButtonPANEL, 50);
    lv_obj_set_x(ui_ButtonPANEL, 40);
    lv_obj_set_y(ui_ButtonPANEL, 106);
    lv_obj_set_align(ui_ButtonPANEL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPANEL, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonPANEL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonPANEL, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPANEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPANEL, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonPANEL, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelPANEL = lv_label_create(ui_ButtonPANEL);
    lv_obj_set_width(ui_LabelPANEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPANEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelPANEL, 2);
    lv_obj_set_x(ui_LabelPANEL, lv_pct(0));
    lv_obj_set_align(ui_LabelPANEL, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelPANEL, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelPANEL, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelPANEL, "PANEL");
    lv_obj_set_style_text_font(ui_LabelPANEL, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonDEFROST = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonDEFROST, 61);
    lv_obj_set_height(ui_ButtonDEFROST, 50);
    lv_obj_set_x(ui_ButtonDEFROST, 110);
    lv_obj_set_y(ui_ButtonDEFROST, 106);
    lv_obj_set_align(ui_ButtonDEFROST, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonDEFROST, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonDEFROST, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonDEFROST, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonDEFROST, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonDEFROST, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonDEFROST, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelDEFROST = lv_label_create(ui_ButtonDEFROST);
    lv_obj_set_width(ui_LabelDEFROST, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDEFROST, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelDEFROST, 2);
    lv_obj_set_x(ui_LabelDEFROST, lv_pct(0));
    lv_obj_set_align(ui_LabelDEFROST, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelDEFROST, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelDEFROST, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelDEFROST, "DEFROST");
    lv_obj_set_style_text_font(ui_LabelDEFROST, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSCREEN2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonSCREEN2, 100);
    lv_obj_set_height(ui_ButtonSCREEN2, 50);
    lv_obj_set_x(ui_ButtonSCREEN2, 183);
    lv_obj_set_y(ui_ButtonSCREEN2, -128);
    lv_obj_set_align(ui_ButtonSCREEN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSCREEN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonSCREEN2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_ButtonSCREEN2);
    lv_image_set_src(ui_Image1, &ui_img_settings_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image1, -2);
    lv_obj_set_y(ui_Image1, 2);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonREARDEF = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonREARDEF, 61);
    lv_obj_set_height(ui_ButtonREARDEF, 50);
    lv_obj_set_x(ui_ButtonREARDEF, 110);
    lv_obj_set_y(ui_ButtonREARDEF, 42);
    lv_obj_set_align(ui_ButtonREARDEF, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonREARDEF, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonREARDEF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonREARDEF, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonREARDEF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonREARDEF, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonREARDEF, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelREARDEFROST = lv_label_create(ui_ButtonREARDEF);
    lv_obj_set_width(ui_LabelREARDEFROST, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelREARDEFROST, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelREARDEFROST, 2);
    lv_obj_set_x(ui_LabelREARDEFROST, lv_pct(0));
    lv_obj_set_align(ui_LabelREARDEFROST, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelREARDEFROST, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelREARDEFROST, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelREARDEFROST, "REAR\nDEFROST");
    lv_obj_set_style_text_font(ui_LabelREARDEFROST, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLEFTTEMP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelLEFTTEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLEFTTEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLEFTTEMP, -201);
    lv_obj_set_y(ui_LabelLEFTTEMP, -55);
    lv_obj_set_align(ui_LabelLEFTTEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLEFTTEMP, "15");
    lv_obj_set_style_text_font(ui_LabelLEFTTEMP, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabellRIGHTTEMP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabellRIGHTTEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabellRIGHTTEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabellRIGHTTEMP, 201);
    lv_obj_set_y(ui_LabellRIGHTTEMP, -56);
    lv_obj_set_align(ui_LabellRIGHTTEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabellRIGHTTEMP, "15");
    lv_obj_set_style_text_font(ui_LabellRIGHTTEMP, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabellFanSegment = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabellFanSegment, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabellFanSegment, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabellFanSegment, 21);
    lv_obj_set_y(ui_LabellFanSegment, -15);
    lv_obj_set_align(ui_LabellFanSegment, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabellFanSegment, "15");
    lv_obj_set_style_text_font(ui_LabellFanSegment, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFANSPEED = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelFANSPEED, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFANSPEED, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFANSPEED, -63);
    lv_obj_set_y(ui_LabelFANSPEED, -8);
    lv_obj_set_align(ui_LabelFANSPEED, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFANSPEED, "FANSPEED");
    lv_obj_set_style_text_font(ui_LabelFANSPEED, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRecirc = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonRecirc, 61);
    lv_obj_set_height(ui_ButtonRecirc, 50);
    lv_obj_set_x(ui_ButtonRecirc, 40);
    lv_obj_set_y(ui_ButtonRecirc, 42);
    lv_obj_set_align(ui_ButtonRecirc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRecirc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonRecirc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRecirc, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRecirc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonRecirc, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonRecirc, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelRecirc = lv_label_create(ui_ButtonRecirc);
    lv_obj_set_width(ui_LabelRecirc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRecirc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelRecirc, 2);
    lv_obj_set_x(ui_LabelRecirc, lv_pct(0));
    lv_obj_set_align(ui_LabelRecirc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelRecirc, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelRecirc, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelRecirc, "RECIRC");
    lv_obj_set_style_text_font(ui_LabelRecirc, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRearhvac = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonRearhvac, 61);
    lv_obj_set_height(ui_ButtonRearhvac, 50);
    lv_obj_set_x(ui_ButtonRearhvac, -34);
    lv_obj_set_y(ui_ButtonRearhvac, 42);
    lv_obj_set_align(ui_ButtonRearhvac, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRearhvac, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonRearhvac, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRearhvac, lv_color_hex(0x111FBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRearhvac, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonRearhvac, lv_color_hex(0x22D043), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ButtonRearhvac, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelREARhvac = lv_label_create(ui_ButtonRearhvac);
    lv_obj_set_width(ui_LabelREARhvac, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelREARhvac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelREARhvac, 2);
    lv_obj_set_x(ui_LabelREARhvac, lv_pct(0));
    lv_obj_set_align(ui_LabelREARhvac, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LabelREARhvac, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LabelREARhvac, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_LabelREARhvac, "REAR\nHVAC");
    lv_obj_set_style_text_font(ui_LabelREARhvac, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonAC, ui_event_ButtonAC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Sliderfan, ui_event_Sliderfan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonFLOOR, ui_event_ButtonFLOOR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonPANEL, ui_event_ButtonPANEL, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonDEFROST, ui_event_ButtonDEFROST, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSCREEN2, ui_event_ButtonSCREEN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonREARDEF, ui_event_ButtonREARDEF, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRecirc, ui_event_ButtonRecirc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelREARhvac, ui_event_LabelREARhvac, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRearhvac, ui_event_ButtonRearhvac, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ButtonAC = NULL;
    ui_Labelac = NULL;
    ui_Button2 = NULL;
    ui_Sliderfan = NULL;
    ui_Sliderleft = NULL;
    ui_Sliderright = NULL;
    ui_ButtonFLOOR = NULL;
    ui_LabelFLOOR = NULL;
    ui_ButtonPANEL = NULL;
    ui_LabelPANEL = NULL;
    ui_ButtonDEFROST = NULL;
    ui_LabelDEFROST = NULL;
    ui_ButtonSCREEN2 = NULL;
    ui_Image1 = NULL;
    ui_ButtonREARDEF = NULL;
    ui_LabelREARDEFROST = NULL;
    ui_LabelLEFTTEMP = NULL;
    ui_LabellRIGHTTEMP = NULL;
    ui_LabellFanSegment = NULL;
    ui_LabelFANSPEED = NULL;
    ui_ButtonRecirc = NULL;
    ui_LabelRecirc = NULL;
    ui_ButtonRearhvac = NULL;
    ui_LabelREARhvac = NULL;

}
