// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: test ac1 june 12

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern void ui_event_ButtonHVACSCREEN(lv_event_t * e);
extern lv_obj_t * ui_ButtonHVACSCREEN;
extern lv_obj_t * ui_LabelHVACSCREEN;
extern void ui_event_ButtonDOWN(lv_event_t * e);
extern lv_obj_t * ui_ButtonDOWN;
extern lv_obj_t * ui_LabelDOWN;
extern void ui_event_ButtonUP(lv_event_t * e);
extern lv_obj_t * ui_ButtonUP;
extern lv_obj_t * ui_LabelUP;
extern void ui_event_ButtonRIGHT(lv_event_t * e);
extern lv_obj_t * ui_ButtonRIGHT;
extern lv_obj_t * ui_LabelRIGHT;
extern void ui_event_ButtonLEFT(lv_event_t * e);
extern lv_obj_t * ui_ButtonLEFT;
extern lv_obj_t * ui_LabelLEFT;
extern void ui_event_ButtonENTER(lv_event_t * e);
extern lv_obj_t * ui_ButtonENTER;
extern lv_obj_t * ui_LabelENTER;
extern void ui_event_ButtonLEFTVENT(lv_event_t * e);
extern lv_obj_t * ui_ButtonLEFTVENT;
extern lv_obj_t * ui_LabelLEFTVENT;
extern void ui_event_ButtonRIGHTVENT(lv_event_t * e);
extern lv_obj_t * ui_ButtonRIGHTVENT;
extern lv_obj_t * ui_LabelRIGHTVENT;
extern void ui_event_ButtonHUD(lv_event_t * e);
extern lv_obj_t * ui_ButtonHUD;
extern lv_obj_t * ui_LabelHUD;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

