// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: test ac1 june 12

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_ButtonAC(lv_event_t * e);
extern lv_obj_t * ui_ButtonAC;
extern lv_obj_t * ui_Labelac;
extern lv_obj_t * ui_Button2;
extern void ui_event_Sliderfan(lv_event_t * e);
extern lv_obj_t * ui_Sliderfan;
extern lv_obj_t * ui_Sliderleft;
extern lv_obj_t * ui_Sliderright;
extern void ui_event_ButtonFLOOR(lv_event_t * e);
extern lv_obj_t * ui_ButtonFLOOR;
extern lv_obj_t * ui_LabelFLOOR;
extern void ui_event_ButtonPANEL(lv_event_t * e);
extern lv_obj_t * ui_ButtonPANEL;
extern lv_obj_t * ui_LabelPANEL;
extern void ui_event_ButtonDEFROST(lv_event_t * e);
extern lv_obj_t * ui_ButtonDEFROST;
extern lv_obj_t * ui_LabelDEFROST;
extern void ui_event_ButtonSCREEN2(lv_event_t * e);
extern lv_obj_t * ui_ButtonSCREEN2;
extern lv_obj_t * ui_Image1;
extern void ui_event_ButtonREARDEF(lv_event_t * e);
extern lv_obj_t * ui_ButtonREARDEF;
extern lv_obj_t * ui_LabelREARDEFROST;
extern lv_obj_t * ui_LabelLEFTTEMP;
extern lv_obj_t * ui_LabellRIGHTTEMP;
extern lv_obj_t * ui_LabellFanSegment;
extern lv_obj_t * ui_LabelFANSPEED;
extern void ui_event_ButtonRecirc(lv_event_t * e);
extern lv_obj_t * ui_ButtonRecirc;
extern lv_obj_t * ui_LabelRecirc;
extern void ui_event_ButtonRearhvac(lv_event_t * e);
extern lv_obj_t * ui_ButtonRearhvac;
extern void ui_event_LabelREARhvac(lv_event_t * e);
extern lv_obj_t * ui_LabelREARhvac;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

